const UserActionTypes = {
    SIGN_UP_START: '@@user/SIGN_UP_START',
    SIGN_UP_SUCCESS: '@@user/SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: '@@user/SIGN_UP_FAILURE',
    RESEND_EMAIL: '@@user/RESEND_EMAIL',
    CONFIRM_EMAIL:'@@user/CONFIRM_EMAIL',
    CONFIRM_EMAIL_SUCCESS: '@@user//CONFIRM_EMAIL_SUCCESS',
    CONFIRM_EMAIL_FAILURE: '@@user//CONFIRM_EMAIL_FAILURE'
}

export default UserActionTypes;